apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    zhoujun-debug-20250326: v0
  name: prover-ceremony124
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prover-ceremony124
  template:
    metadata:
      labels:
        app: prover-ceremony124
        zhoujun-debug-20250326: v0
    spec:
      containers:
      - args:
        - -listen=:8080
        - -text=HELLOOO
        image: hashicorp/http-echo
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
