apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: vk-monitoring-router
  labels:
    zhoujun-debug-20250326: v0
spec:
  default:
    config:
      httpHealthCheck:
        requestPath: /healthz
      type: HTTP
    logConfig:
      enabled: true
  targetRef:
    group: ""
    kind: Service
    name: vk-monitoring-router
