#
# We don't want this resource to be managed by `internal-ops` automation...
#
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: forward-to-latest
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: keyless-prover
    sectionName: https
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /v0/prove
    backendRefs:
    - group: ""
      kind: Service
      name: prover-ceremony123 # Updated by `onchain-vk-monitor` once it sees ceremony124 on chain.
      port: 80
