apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: router-service-reader-binding
subjects:
  - kind: ServiceAccount
    name: vk-monitoring-router
    namespace: keyless-devnet
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
