apiVersion: v1
kind: Service
metadata:
  name: prover-ceremony124
  labels:
    zhoujun-debug-20250326: v0
spec:
  type: NodePort
  selector:
    app: prover-ceremony124
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 80
